# Generated by Django 3.0.3 on 2020-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMarketApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Email', models.CharField(max_length=264)),
                ('Text', models.TextField(max_length=1000, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StockValues',
        ),
    ]
